### ISSUE TITLE
Unbundle?

### ISSUE THREAD

**Issue by Thundros** [mpaccione/everest_flight_sim#2]
Hello! I would like to study the source. Can you please unbundle this? Thank you very much!

**Comment by mpaccione** [comment]
Currently at the time of writing the app is bundled with this command:

`watchify app.js -o dist/bundle.js`

You can look on the github repo at the files, specifically app.js. You will see the commonjs imports and the you can inspect the class code I've written so far.

**Comment by Thundros** [comment]
@mpaccione Hi, this is a WONDERFUL demo! EXCELLENT job! Keep up the great work! Although, I had one question. Once I uncomment the shaders, how do I use the shaders to texture splat the terrain using an RGB texture? Thank You!

**Comment by mpaccione** [comment]
Thank you. The physics engine need some work for sure. I don't know enough mathematics unfortunately. So if you know anyone interested in collaborating with me on it please point them this way.

The commented out shaders are for the AnimatedProceduralTerrain class... which I haven't tested. I integrated code from this demo: https://threejs.org/examples/webgl_terrain_dynamic.html

The shader in this basically pipes a delta value through the vertices of the "ground". Please check the source code from the link above to deduce best implementaton.

As far as the normal ProceduralTerrain it uses code from this demo: https://threejs.org/examples/?q=terrain#webgl_geometry_terrain

The ProceduralTerrain uses SimplexNoise and creates a 2D heightmap via a canvas and then bases the texture color of the vertexes/faces based on the height values. There is some issue with it not working correctly so far. I will be looking into it next month. Currently I am trying to get the physics dynamics as playable as possible in the meantime.

You may want to check this tutorial on medium for creating texture from a 2D canvas height map. It is was I intend to compare when fixing the issue in the future.

https://medium.com/@joshmarinacci/low-poly-style-terrain-generation-8a017ab02e7b

Thank you for your interest and please invite others to the repo to help out :)

**Comment by Thundros** [comment]
@mpaccione Did you try using physijs for the physics? Also, I have tried everything to get the texture splatting to show up.

**Comment by mpaccione** [comment]
@Thundros Thank you for the physijs reference. I was unaware. I will take a look in the future on whether integrating that or improving my current physics engine is better.

In regards to the texture... I have changed the branch names and will be creating a debugger-simulation branch which will feature a texture. I will post here again when that has been fixed.

**Comment by Thundros** [comment]
You're welcome, I just wish to see the ability to use an RGBA ( Red Green Blue Alpha ) splat map in order to draw textures on the terrain :)

**Comment by mpaccione** [comment]
Well I will surely get around to it. Since I don't have much shader experience I am leaving it for a bit later. Right now I am working on creating the cockpit instrument gauges and tying them in to the pitch, roll, yaw, and acceleration integers using a 2D Canvas library. https://konvajs.org/

This RGBA Splat Map shader example should help you! 
https://stackoverflow.com/questions/18880715/texture-splatting-with-three-js

**Comment by Thundros** [comment]
@mpaccione Thank you, but I have already tried that one. The problem is, I can't draw on an RGBA splatmap image & load the textures onto the terrain with that.

**Comment by mpaccione** [comment]
I have written a splat map shader. 
I believe if you take a look you will be able to modify for your needs.

In terrain.js
